spring:
  datasource:
    driverClassName: org.apache.derby.jdbc.ClientDriver
    url: jdbc:derby://localhost:1527/School;create=true;user=root;password=root
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.DerbyDialect
    show-sql: true
    hibernate:
       ddl-auto: none
  cache:
    type: redis
    host: 127.0.0.1
    port: 6379

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  server:
    jsp-servlet:
      init-parameters:
        development=true:


