spring:
  datasource:
    driverClassName: org.apache.derby.jdbc.ClientDriver
    url: jdbc:derby://localhost:1527/School;create=true;user=root;password=root
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.DerbyDialect
    show-sql: true
    hibernate:
       ddl-auto: none
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
  cache:
    type: redis

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  server:
    jsp-servlet:
      init-parameters:
        development=true:


